/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/groups/public/")
    }

    maven {
        url = uri("https://repo.azisaba.net/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.acrylicstyle.xyz/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.org.projectlombok.lombok)
    compileOnly(libs.net.azisaba.azisabaachievements.api)
}

group = "net.azisaba"
version = "1.3.0"
description = "AzisabaLobby"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
