name: ${project.name}
main: net.azisaba.lobby.AzisabaLobby
version: ${project.version}
author: siloneco
description: ${project.description}
api-version: 1.13

permissions:
  azisabalobby.allow-interact-flower-pot:
    default: op
    description: 植木鉢の破壊に関するパーミッションです。
  azisabalobby.allow-destroy-painting:
    default: op
    description: 額縁の破壊に関するパーミッションです。
